json_feeds:
  - title: Galaxy News
    url: https://galaxyproject.org/news/feed.json
    list_key: "news"
    format: "{tease}\n{link}\n{images}"

    # Media channels get grouped based on whether their posts might need separate editing.
    # One output file with shared post body will be created for each group, but we'd often
    # want to edit bluesky posts separately because their different character limit.
    media:
      group1:
        linkedin-galaxyproject:
          - global
          - us
      group2:
        bluesky-galaxyproject:
          - global
          - us
      group3:
        mastodon-galaxyproject:
          - global
          - us
        mastodon-eu-freiburg:
          - all-eu
          - eu
          - freiburg
        matrix-eu-announce:
          - all-eu
          - eu

    # Media conflicts can be used to avoid unwanted double-posting. For every conflict,
    # the channel provided as the key, if selected, will prevent posting to all channels
    # listed below it.

    media_conflicts:
      mastodon-galaxyproject:
        - mastodon-eu-freiburg

    mentions:
      mastodon-galaxyproject:
        all-eu:
          - galaxyfreiburg@bawü.social
        eu:
          - galaxyfreiburg@bawü.social
        freiburg:
          - galaxyfreiburg@bawü.social
      mastodon-eu-freiburg:
        global:
          - galaxyproject@mstdn.science
        us:
          - galaxyproject@mstdn.science

    hashtags:
      mastodon-eu-freiburg:
        all:
          - UseGalaxy
          - GalaxyProject
          - EOSC
        esg:
          - EuroScienceGateway
        freiburg:
          - UniFreiburg
      mastodon-galaxyproject:
        all:
          - UseGalaxy
          - GalaxyProject
        esg:
          - EuroScienceGateway
        eu:
          - EOSC
      bluesky-galaxyproject:
        all:
          - UseGalaxy
          - GalaxyProject
        esg:
          - EuroScienceGateway
        eu:
          - EOSC
      linkedin-galaxyproject:
        all:
          - UseGalaxy
          - GalaxyProject
        esg:
          - EuroScienceGateway
        eu:
          - EOSC

  - title: "Galaxy Events"
    url: https://galaxyproject.org/events/feed.json
    list_key: "events"
    format: "📣 {title}\n\n{tease}\n\n📍 {location}\n📅 {date}\n🔗 More info & registration: {link}\n\n{images}"

    media:
      group1:
        linkedin-galaxyproject:
          - global
          - us
      group2:
        bluesky-galaxyproject:
          - global
          - us
      group3:
        mastodon-galaxyproject:
          - global
          - us
        mastodon-eu-freiburg:
          - all-eu
          - eu
          - freiburg
        matrix-eu-announce:
          - all-eu
          - eu

    media_conflicts:
      mastodon-galaxyproject:
        - mastodon-eu-freiburg

    mentions:
      mastodon-galaxyproject:
        all-eu:
          - galaxyfreiburg@bawü.social
        eu:
          - galaxyfreiburg@bawü.social
        freiburg:
          - galaxyfreiburg@bawü.social
      mastodon-eu-freiburg:
        global:
          - galaxyproject@mstdn.science
        us:
          - galaxyproject@mstdn.science

    hashtags:
      mastodon-eu-freiburg:
        all:
          - UseGalaxy
          - GalaxyProject
          - EOSC
        esg:
          - EuroScienceGateway
        freiburg:
          - UniFreiburg
      mastodon-galaxyproject:
        all:
          - UseGalaxy
          - GalaxyProject
        esg:
          - EuroScienceGateway
        eu:
          - EOSC
      bluesky-galaxyproject:
        all:
          - UseGalaxy
          - GalaxyProject
        esg:
          - EuroScienceGateway
        eu:
          - EOSC
      linkedin-galaxyproject:
        all:
          - UseGalaxy
          - GalaxyProject
        esg:
          - EuroScienceGateway
        eu:
          - EOSC

# youtube_channels:
#   - channel: "https://www.youtube.com/c/galaxyproject"
#     format: "🎥 New YouTube Video Released!\n\n{title}\n\n🔗 Watch it now: {link}"


# citations:
#   - zotero_group_id: 1732893
#     tag: ">UseGalaxy.eu || >RNA Workbench || RNA workbench || >ASaiM || >Live EU || >Proteomics EU || >Metagenomics EU || >ML Workbench || >ChemicalToolbox"
#     format: "📰 New publication Released!\n\n{title}\nBy: {creators}\n{url}"
