name: Create PR for youtube videos

on:
  schedule:
    - cron: "00 00 * * *"

  workflow_dispatch:
    inputs:
      days:
        description: "Number of days before today to check for new videos"
        required: false
        default: "5"

jobs:
  youtube-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: "usegalaxy-eu"
          repositories: "galaxy-social"

      - name: Run python script
        env:
          GALAXY_SOCIAL_BOT_TOKEN: ${{ steps.generate-token.outputs.token }}
          REPO: "usegalaxy-eu/galaxy-social"
          DAYS: ${{ github.event.inputs.days || '5' }}
        run: python -u app/youtube_bot.py
